# ----- Properties -----

jedis:
  host: localhost
  port: 6379

quarkus:
  rest-client:
    covid-api:
      url: https://api.covid19api.com
  datasource:
    db-kind: postgresql
    username: postgres
    password: root
    jdbc:
      url: jdbc:postgresql://localhost:5432/quarkus-covid-api
  hibernate-orm:
    database:
      generation: validate
  liquibase:
    change-log: db/changelog/changelog.xml
    migrate-at-start: true


"%test":
  quarkus:
    datasource:
      db-kind: postgresql
      username: postgres
      password: root
      jdbc:
        url: jdbc:postgresql://localhost:5432/quarkus-covid-api-test
    hibernate-orm:
      database:
        generation: create-drop
    liquibase:
      change-log: db/changelog/changelog.xml
      migrate-at-start: true